name: CI/CD Pipeline for Backend of E-Deliver App

on:
  push:
    branches: ["main"]
    paths:
      - EDeliver-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml
  pull_request:
    branches: ["main"]
    paths:
      - EDeliver-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile Backend App
        run: |
          cd EDeliver-backend
          mvn clean compile -DskipTests=true

  Test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: edeliver
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=20s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 30`; do
            if mysqladmin ping -h "127.0.0.1" --silent; then
              echo "MySQL is up and running"
              exit 0
            fi
            echo -n "."
            sleep 1
          done
          echo "Failed waiting for MySQL"
          exit 1
      - name: Run Unit Tests of Backend App
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/edeliver
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD:
          SPRING_PROFILES_ACTIVE: test # Ensures the 'test' profile is active
        run: |
          cd EDeliver-backend
          mvn test -Dspring.profiles.active=test
          
  Build:
    runs-on: ubuntu-latest
    needs: [Compile, Test]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Backend App
        run: |
          cd EDeliver-backend
          mvn clean package -DskipTests=true
        