name: CI/CD Pipeline for Backend of E-Deliver App

on:
  push:
    branches: ["main"]
    paths:
      - EDeliver-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml
  pull_request:
    branches: ["main"]
    paths:
      - EDeliver-backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile Backend App
        run: |
          cd EDeliver-backend
          mvn clean compile -DskipTests=true

  Build:
    runs-on: ubuntu-latest
    needs: [Compile, Test]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Backend App
        run: |
          cd EDeliver-backend
          mvn clean package -DskipTests=true
        
